name: TempFly
main: com.moneybags.tempfly.TempFly
softdepend: [Essentials, PlaceholderAPI, Vault, WorldGuard, WorldEdit]
api-version: 1.13
version: 3.2.0
commands:
    tempfly:
        description: Base command
        aliases: [tfly, tf]


