name: Build JAR

on:
  push:
    branches:
      - Master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Install Maven
        run: sudo apt-get update && sudo apt-get install -y maven

      - name: Build with Maven
        run: mvn clean package

      - name: Upload JAR
        uses: actions/upload-artifact@v4
        with:
          name: TempFly
          path: target/*.jar
