name: Build JAR

on:
  workflow_dispatch:
    inputs:
      enviroment:
        description: 'Compile'
        required: false
        default: 'Staging'
      userSuffix:
        description: 'Optional Suffix'
        required: false
        default: ''

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      userSuffix: ${{ github.event.inputs.userSuffix != '' && github.event.inputs.userSuffix || format('TempFly-{0}', github.event.inputs.userSuffix) || 'TempFly' }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Install Maven
        run: sudo apt-get update && sudo apt-get install -y maven

      - name: Build with Maven
        run: mvn -f ./TempFly/pom.xml clean package

      - name: Upload JAR
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.userSuffix }}
          path: /home/runner/work/TempFly_XCraft/TempFly_XCraft/TempFly/target/*.jar
